export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
};

export default function BlogsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
